#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_TimViec")]
	public partial class tvDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertaccount(account instance);
    partial void Updateaccount(account instance);
    partial void Deleteaccount(account instance);
    partial void Insertbaidang(baidang instance);
    partial void Updatebaidang(baidang instance);
    partial void Deletebaidang(baidang instance);
    partial void Insertchitietbd(chitietbd instance);
    partial void Updatechitietbd(chitietbd instance);
    partial void Deletechitietbd(chitietbd instance);
    partial void Insertcongviec(congviec instance);
    partial void Updatecongviec(congviec instance);
    partial void Deletecongviec(congviec instance);
    partial void Insertdangky(dangky instance);
    partial void Updatedangky(dangky instance);
    partial void Deletedangky(dangky instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void Insertloaicongviec(loaicongviec instance);
    partial void Updateloaicongviec(loaicongviec instance);
    partial void Deleteloaicongviec(loaicongviec instance);
    partial void Insertquantri(quantri instance);
    partial void Updatequantri(quantri instance);
    partial void Deletequantri(quantri instance);
    partial void Inserttuyendung(tuyendung instance);
    partial void Updatetuyendung(tuyendung instance);
    partial void Deletetuyendung(tuyendung instance);
    #endregion
		
		public tvDataContext() : 
				base(global::LinQ.Properties.Settings.Default.QL_TimViecConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public tvDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tvDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tvDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tvDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<account> accounts
		{
			get
			{
				return this.GetTable<account>();
			}
		}
		
		public System.Data.Linq.Table<baidang> baidangs
		{
			get
			{
				return this.GetTable<baidang>();
			}
		}
		
		public System.Data.Linq.Table<chitietbd> chitietbds
		{
			get
			{
				return this.GetTable<chitietbd>();
			}
		}
		
		public System.Data.Linq.Table<congviec> congviecs
		{
			get
			{
				return this.GetTable<congviec>();
			}
		}
		
		public System.Data.Linq.Table<dangky> dangkies
		{
			get
			{
				return this.GetTable<dangky>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<loaicongviec> loaicongviecs
		{
			get
			{
				return this.GetTable<loaicongviec>();
			}
		}
		
		public System.Data.Linq.Table<quantri> quantris
		{
			get
			{
				return this.GetTable<quantri>();
			}
		}
		
		public System.Data.Linq.Table<tuyendung> tuyendungs
		{
			get
			{
				return this.GetTable<tuyendung>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.account")]
	public partial class account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
		private int _type;
		
		private System.Nullable<int> _tinhtrang;
		
		private EntitySet<KhachHang> _KhachHangs;
		
		private EntitySet<quantri> _quantris;
		
		private EntitySet<tuyendung> _tuyendungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    partial void OntinhtrangChanging(System.Nullable<int> value);
    partial void OntinhtrangChanged();
    #endregion
		
		public account()
		{
			this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
			this._quantris = new EntitySet<quantri>(new Action<quantri>(this.attach_quantris), new Action<quantri>(this.detach_quantris));
			this._tuyendungs = new EntitySet<tuyendung>(new Action<tuyendung>(this.attach_tuyendungs), new Action<tuyendung>(this.detach_tuyendungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="Int")]
		public System.Nullable<int> tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="account_KhachHang", Storage="_KhachHangs", ThisKey="username", OtherKey="username")]
		public EntitySet<KhachHang> KhachHangs
		{
			get
			{
				return this._KhachHangs;
			}
			set
			{
				this._KhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="account_quantri", Storage="_quantris", ThisKey="username", OtherKey="username")]
		public EntitySet<quantri> quantris
		{
			get
			{
				return this._quantris;
			}
			set
			{
				this._quantris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="account_tuyendung", Storage="_tuyendungs", ThisKey="username", OtherKey="username")]
		public EntitySet<tuyendung> tuyendungs
		{
			get
			{
				return this._tuyendungs;
			}
			set
			{
				this._tuyendungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.account = this;
		}
		
		private void detach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.account = null;
		}
		
		private void attach_quantris(quantri entity)
		{
			this.SendPropertyChanging();
			entity.account = this;
		}
		
		private void detach_quantris(quantri entity)
		{
			this.SendPropertyChanging();
			entity.account = null;
		}
		
		private void attach_tuyendungs(tuyendung entity)
		{
			this.SendPropertyChanging();
			entity.account = this;
		}
		
		private void detach_tuyendungs(tuyendung entity)
		{
			this.SendPropertyChanging();
			entity.account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.baidang")]
	public partial class baidang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mabd;
		
		private string _manhatd;
		
		private string _macv;
		
		private string _title;
		
		private string _image;
		
		private System.Nullable<int> _luong;
		
		private System.Nullable<System.DateTime> _ngaydang;
		
		private EntitySet<chitietbd> _chitietbds;
		
		private EntitySet<dangky> _dangkies;
		
		private EntityRef<congviec> _congviec;
		
		private EntityRef<tuyendung> _tuyendung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabdChanging(string value);
    partial void OnmabdChanged();
    partial void OnmanhatdChanging(string value);
    partial void OnmanhatdChanged();
    partial void OnmacvChanging(string value);
    partial void OnmacvChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnluongChanging(System.Nullable<int> value);
    partial void OnluongChanged();
    partial void OnngaydangChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydangChanged();
    #endregion
		
		public baidang()
		{
			this._chitietbds = new EntitySet<chitietbd>(new Action<chitietbd>(this.attach_chitietbds), new Action<chitietbd>(this.detach_chitietbds));
			this._dangkies = new EntitySet<dangky>(new Action<dangky>(this.attach_dangkies), new Action<dangky>(this.detach_dangkies));
			this._congviec = default(EntityRef<congviec>);
			this._tuyendung = default(EntityRef<tuyendung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabd", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mabd
		{
			get
			{
				return this._mabd;
			}
			set
			{
				if ((this._mabd != value))
				{
					this.OnmabdChanging(value);
					this.SendPropertyChanging();
					this._mabd = value;
					this.SendPropertyChanged("mabd");
					this.OnmabdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhatd", DbType="NVarChar(20)")]
		public string manhatd
		{
			get
			{
				return this._manhatd;
			}
			set
			{
				if ((this._manhatd != value))
				{
					if (this._tuyendung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanhatdChanging(value);
					this.SendPropertyChanging();
					this._manhatd = value;
					this.SendPropertyChanged("manhatd");
					this.OnmanhatdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macv", DbType="NVarChar(20)")]
		public string macv
		{
			get
			{
				return this._macv;
			}
			set
			{
				if ((this._macv != value))
				{
					if (this._congviec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacvChanging(value);
					this.SendPropertyChanging();
					this._macv = value;
					this.SendPropertyChanged("macv");
					this.OnmacvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(100)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(200)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong", DbType="Int")]
		public System.Nullable<int> luong
		{
			get
			{
				return this._luong;
			}
			set
			{
				if ((this._luong != value))
				{
					this.OnluongChanging(value);
					this.SendPropertyChanging();
					this._luong = value;
					this.SendPropertyChanged("luong");
					this.OnluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="Date")]
		public System.Nullable<System.DateTime> ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this.OnngaydangChanging(value);
					this.SendPropertyChanging();
					this._ngaydang = value;
					this.SendPropertyChanged("ngaydang");
					this.OnngaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="baidang_chitietbd", Storage="_chitietbds", ThisKey="mabd", OtherKey="mabd")]
		public EntitySet<chitietbd> chitietbds
		{
			get
			{
				return this._chitietbds;
			}
			set
			{
				this._chitietbds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="baidang_dangky", Storage="_dangkies", ThisKey="mabd", OtherKey="mabd")]
		public EntitySet<dangky> dangkies
		{
			get
			{
				return this._dangkies;
			}
			set
			{
				this._dangkies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="congviec_baidang", Storage="_congviec", ThisKey="macv", OtherKey="macv", IsForeignKey=true)]
		public congviec congviec
		{
			get
			{
				return this._congviec.Entity;
			}
			set
			{
				congviec previousValue = this._congviec.Entity;
				if (((previousValue != value) 
							|| (this._congviec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._congviec.Entity = null;
						previousValue.baidangs.Remove(this);
					}
					this._congviec.Entity = value;
					if ((value != null))
					{
						value.baidangs.Add(this);
						this._macv = value.macv;
					}
					else
					{
						this._macv = default(string);
					}
					this.SendPropertyChanged("congviec");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tuyendung_baidang", Storage="_tuyendung", ThisKey="manhatd", OtherKey="manhatd", IsForeignKey=true)]
		public tuyendung tuyendung
		{
			get
			{
				return this._tuyendung.Entity;
			}
			set
			{
				tuyendung previousValue = this._tuyendung.Entity;
				if (((previousValue != value) 
							|| (this._tuyendung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tuyendung.Entity = null;
						previousValue.baidangs.Remove(this);
					}
					this._tuyendung.Entity = value;
					if ((value != null))
					{
						value.baidangs.Add(this);
						this._manhatd = value.manhatd;
					}
					else
					{
						this._manhatd = default(string);
					}
					this.SendPropertyChanged("tuyendung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietbds(chitietbd entity)
		{
			this.SendPropertyChanging();
			entity.baidang = this;
		}
		
		private void detach_chitietbds(chitietbd entity)
		{
			this.SendPropertyChanging();
			entity.baidang = null;
		}
		
		private void attach_dangkies(dangky entity)
		{
			this.SendPropertyChanging();
			entity.baidang = this;
		}
		
		private void detach_dangkies(dangky entity)
		{
			this.SendPropertyChanging();
			entity.baidang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietbd")]
	public partial class chitietbd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _mabd;
		
		private string _title;
		
		private string _tencty;
		
		private string _yeucau;
		
		private string _noidung;
		
		private EntityRef<baidang> _baidang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmabdChanging(string value);
    partial void OnmabdChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OntenctyChanging(string value);
    partial void OntenctyChanged();
    partial void OnyeucauChanging(string value);
    partial void OnyeucauChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    #endregion
		
		public chitietbd()
		{
			this._baidang = default(EntityRef<baidang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabd", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string mabd
		{
			get
			{
				return this._mabd;
			}
			set
			{
				if ((this._mabd != value))
				{
					if (this._baidang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmabdChanging(value);
					this.SendPropertyChanging();
					this._mabd = value;
					this.SendPropertyChanged("mabd");
					this.OnmabdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(150)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tencty", DbType="NVarChar(100)")]
		public string tencty
		{
			get
			{
				return this._tencty;
			}
			set
			{
				if ((this._tencty != value))
				{
					this.OntenctyChanging(value);
					this.SendPropertyChanging();
					this._tencty = value;
					this.SendPropertyChanged("tencty");
					this.OntenctyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yeucau", DbType="NVarChar(500)")]
		public string yeucau
		{
			get
			{
				return this._yeucau;
			}
			set
			{
				if ((this._yeucau != value))
				{
					this.OnyeucauChanging(value);
					this.SendPropertyChanging();
					this._yeucau = value;
					this.SendPropertyChanged("yeucau");
					this.OnyeucauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(500)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="baidang_chitietbd", Storage="_baidang", ThisKey="mabd", OtherKey="mabd", IsForeignKey=true)]
		public baidang baidang
		{
			get
			{
				return this._baidang.Entity;
			}
			set
			{
				baidang previousValue = this._baidang.Entity;
				if (((previousValue != value) 
							|| (this._baidang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._baidang.Entity = null;
						previousValue.chitietbds.Remove(this);
					}
					this._baidang.Entity = value;
					if ((value != null))
					{
						value.chitietbds.Add(this);
						this._mabd = value.mabd;
					}
					else
					{
						this._mabd = default(string);
					}
					this.SendPropertyChanged("baidang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.congviec")]
	public partial class congviec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _macv;
		
		private string _tencv;
		
		private string _maloai;
		
		private EntitySet<baidang> _baidangs;
		
		private EntityRef<loaicongviec> _loaicongviec;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmacvChanging(string value);
    partial void OnmacvChanged();
    partial void OntencvChanging(string value);
    partial void OntencvChanged();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    #endregion
		
		public congviec()
		{
			this._baidangs = new EntitySet<baidang>(new Action<baidang>(this.attach_baidangs), new Action<baidang>(this.detach_baidangs));
			this._loaicongviec = default(EntityRef<loaicongviec>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macv", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string macv
		{
			get
			{
				return this._macv;
			}
			set
			{
				if ((this._macv != value))
				{
					this.OnmacvChanging(value);
					this.SendPropertyChanging();
					this._macv = value;
					this.SendPropertyChanged("macv");
					this.OnmacvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tencv", DbType="NVarChar(100)")]
		public string tencv
		{
			get
			{
				return this._tencv;
			}
			set
			{
				if ((this._tencv != value))
				{
					this.OntencvChanging(value);
					this.SendPropertyChanging();
					this._tencv = value;
					this.SendPropertyChanged("tencv");
					this.OntencvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="NVarChar(20)")]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					if (this._loaicongviec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="congviec_baidang", Storage="_baidangs", ThisKey="macv", OtherKey="macv")]
		public EntitySet<baidang> baidangs
		{
			get
			{
				return this._baidangs;
			}
			set
			{
				this._baidangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaicongviec_congviec", Storage="_loaicongviec", ThisKey="maloai", OtherKey="maloai", IsForeignKey=true)]
		public loaicongviec loaicongviec
		{
			get
			{
				return this._loaicongviec.Entity;
			}
			set
			{
				loaicongviec previousValue = this._loaicongviec.Entity;
				if (((previousValue != value) 
							|| (this._loaicongviec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaicongviec.Entity = null;
						previousValue.congviecs.Remove(this);
					}
					this._loaicongviec.Entity = value;
					if ((value != null))
					{
						value.congviecs.Add(this);
						this._maloai = value.maloai;
					}
					else
					{
						this._maloai = default(string);
					}
					this.SendPropertyChanged("loaicongviec");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_baidangs(baidang entity)
		{
			this.SendPropertyChanging();
			entity.congviec = this;
		}
		
		private void detach_baidangs(baidang entity)
		{
			this.SendPropertyChanging();
			entity.congviec = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dangky")]
	public partial class dangky : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _mabd;
		
		private string _makh;
		
		private EntityRef<baidang> _baidang;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmabdChanging(string value);
    partial void OnmabdChanged();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    #endregion
		
		public dangky()
		{
			this._baidang = default(EntityRef<baidang>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabd", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string mabd
		{
			get
			{
				return this._mabd;
			}
			set
			{
				if ((this._mabd != value))
				{
					if (this._baidang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmabdChanging(value);
					this.SendPropertyChanging();
					this._mabd = value;
					this.SendPropertyChanged("mabd");
					this.OnmabdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="NVarChar(20)")]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="baidang_dangky", Storage="_baidang", ThisKey="mabd", OtherKey="mabd", IsForeignKey=true)]
		public baidang baidang
		{
			get
			{
				return this._baidang.Entity;
			}
			set
			{
				baidang previousValue = this._baidang.Entity;
				if (((previousValue != value) 
							|| (this._baidang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._baidang.Entity = null;
						previousValue.dangkies.Remove(this);
					}
					this._baidang.Entity = value;
					if ((value != null))
					{
						value.dangkies.Add(this);
						this._mabd = value.mabd;
					}
					else
					{
						this._mabd = default(string);
					}
					this.SendPropertyChanged("baidang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_dangky", Storage="_KhachHang", ThisKey="makh", OtherKey="makh", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.dangkies.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.dangkies.Add(this);
						this._makh = value.makh;
					}
					else
					{
						this._makh = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makh;
		
		private string _tenkh;
		
		private string _diachi;
		
		private string _sdt;
		
		private string _username;
		
		private EntitySet<dangky> _dangkies;
		
		private EntityRef<account> _account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OntenkhChanging(string value);
    partial void OntenkhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
		
		public KhachHang()
		{
			this._dangkies = new EntitySet<dangky>(new Action<dangky>(this.attach_dangkies), new Action<dangky>(this.detach_dangkies));
			this._account = default(EntityRef<account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkh", DbType="NVarChar(100)")]
		public string tenkh
		{
			get
			{
				return this._tenkh;
			}
			set
			{
				if ((this._tenkh != value))
				{
					this.OntenkhChanging(value);
					this.SendPropertyChanging();
					this._tenkh = value;
					this.SendPropertyChanged("tenkh");
					this.OntenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NVarChar(20)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					if (this._account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_dangky", Storage="_dangkies", ThisKey="makh", OtherKey="makh")]
		public EntitySet<dangky> dangkies
		{
			get
			{
				return this._dangkies;
			}
			set
			{
				this._dangkies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="account_KhachHang", Storage="_account", ThisKey="username", OtherKey="username", IsForeignKey=true)]
		public account account
		{
			get
			{
				return this._account.Entity;
			}
			set
			{
				account previousValue = this._account.Entity;
				if (((previousValue != value) 
							|| (this._account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._account.Entity = null;
						previousValue.KhachHangs.Remove(this);
					}
					this._account.Entity = value;
					if ((value != null))
					{
						value.KhachHangs.Add(this);
						this._username = value.username;
					}
					else
					{
						this._username = default(string);
					}
					this.SendPropertyChanged("account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dangkies(dangky entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_dangkies(dangky entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaicongviec")]
	public partial class loaicongviec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maloai;
		
		private string _tenloai;
		
		private EntitySet<congviec> _congviecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void OntenloaiChanging(string value);
    partial void OntenloaiChanged();
    #endregion
		
		public loaicongviec()
		{
			this._congviecs = new EntitySet<congviec>(new Action<congviec>(this.attach_congviecs), new Action<congviec>(this.detach_congviecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloai", DbType="NVarChar(100)")]
		public string tenloai
		{
			get
			{
				return this._tenloai;
			}
			set
			{
				if ((this._tenloai != value))
				{
					this.OntenloaiChanging(value);
					this.SendPropertyChanging();
					this._tenloai = value;
					this.SendPropertyChanged("tenloai");
					this.OntenloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaicongviec_congviec", Storage="_congviecs", ThisKey="maloai", OtherKey="maloai")]
		public EntitySet<congviec> congviecs
		{
			get
			{
				return this._congviecs;
			}
			set
			{
				this._congviecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_congviecs(congviec entity)
		{
			this.SendPropertyChanging();
			entity.loaicongviec = this;
		}
		
		private void detach_congviecs(congviec entity)
		{
			this.SendPropertyChanging();
			entity.loaicongviec = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quantri")]
	public partial class quantri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maqt;
		
		private string _tenqt;
		
		private string _diachi;
		
		private string _sdt;
		
		private string _username;
		
		private EntityRef<account> _account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaqtChanging(string value);
    partial void OnmaqtChanged();
    partial void OntenqtChanging(string value);
    partial void OntenqtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
		
		public quantri()
		{
			this._account = default(EntityRef<account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maqt", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maqt
		{
			get
			{
				return this._maqt;
			}
			set
			{
				if ((this._maqt != value))
				{
					this.OnmaqtChanging(value);
					this.SendPropertyChanging();
					this._maqt = value;
					this.SendPropertyChanged("maqt");
					this.OnmaqtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenqt", DbType="NVarChar(100)")]
		public string tenqt
		{
			get
			{
				return this._tenqt;
			}
			set
			{
				if ((this._tenqt != value))
				{
					this.OntenqtChanging(value);
					this.SendPropertyChanging();
					this._tenqt = value;
					this.SendPropertyChanged("tenqt");
					this.OntenqtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NVarChar(20)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					if (this._account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="account_quantri", Storage="_account", ThisKey="username", OtherKey="username", IsForeignKey=true)]
		public account account
		{
			get
			{
				return this._account.Entity;
			}
			set
			{
				account previousValue = this._account.Entity;
				if (((previousValue != value) 
							|| (this._account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._account.Entity = null;
						previousValue.quantris.Remove(this);
					}
					this._account.Entity = value;
					if ((value != null))
					{
						value.quantris.Add(this);
						this._username = value.username;
					}
					else
					{
						this._username = default(string);
					}
					this.SendPropertyChanged("account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tuyendung")]
	public partial class tuyendung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manhatd;
		
		private string _tennhatd;
		
		private string _diachi;
		
		private string _sdt;
		
		private string _username;
		
		private EntitySet<baidang> _baidangs;
		
		private EntityRef<account> _account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanhatdChanging(string value);
    partial void OnmanhatdChanged();
    partial void OntennhatdChanging(string value);
    partial void OntennhatdChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
		
		public tuyendung()
		{
			this._baidangs = new EntitySet<baidang>(new Action<baidang>(this.attach_baidangs), new Action<baidang>(this.detach_baidangs));
			this._account = default(EntityRef<account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhatd", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manhatd
		{
			get
			{
				return this._manhatd;
			}
			set
			{
				if ((this._manhatd != value))
				{
					this.OnmanhatdChanging(value);
					this.SendPropertyChanging();
					this._manhatd = value;
					this.SendPropertyChanged("manhatd");
					this.OnmanhatdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhatd", DbType="NVarChar(100)")]
		public string tennhatd
		{
			get
			{
				return this._tennhatd;
			}
			set
			{
				if ((this._tennhatd != value))
				{
					this.OntennhatdChanging(value);
					this.SendPropertyChanging();
					this._tennhatd = value;
					this.SendPropertyChanged("tennhatd");
					this.OntennhatdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NVarChar(20)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					if (this._account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tuyendung_baidang", Storage="_baidangs", ThisKey="manhatd", OtherKey="manhatd")]
		public EntitySet<baidang> baidangs
		{
			get
			{
				return this._baidangs;
			}
			set
			{
				this._baidangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="account_tuyendung", Storage="_account", ThisKey="username", OtherKey="username", IsForeignKey=true)]
		public account account
		{
			get
			{
				return this._account.Entity;
			}
			set
			{
				account previousValue = this._account.Entity;
				if (((previousValue != value) 
							|| (this._account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._account.Entity = null;
						previousValue.tuyendungs.Remove(this);
					}
					this._account.Entity = value;
					if ((value != null))
					{
						value.tuyendungs.Add(this);
						this._username = value.username;
					}
					else
					{
						this._username = default(string);
					}
					this.SendPropertyChanged("account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_baidangs(baidang entity)
		{
			this.SendPropertyChanging();
			entity.tuyendung = this;
		}
		
		private void detach_baidangs(baidang entity)
		{
			this.SendPropertyChanging();
			entity.tuyendung = null;
		}
	}
}
#pragma warning restore 1591
